### ISSUE TITLE
Unfortunately,Pico TTS has stopped

### ISSUE THREAD

**Issue by androidAppGuard** [jonasoreland/runnerup#1109]
**the environment is as follows:**
```
App version: v2.0.3.0
Android version: 6.0
Device: Nexux_5X
```
**The steps to reproduce:**
![26_runnerup_TTS.gif](https://s2.loli.net/2022/05/13/v2KpymrZjUn7kGg.gif)
**The exception log is as follows:**
```
05-13 12:26:17.156 15158-15158/org.runnerup.debug E/TrackerComponentCollection: TTS onInit => RESULT_OK
05-13 12:26:17.156 15158-15158/org.runnerup.debug E/TrackerComponentCollection:  => runCallback()
05-13 12:26:17.156 15158-15158/org.runnerup.debug E/org.runnerup.tracker.Tracker$1: state.set(INITIALIZED)
```

**Comment by gerhardol** [comment]
I do not have any clue why PicoTTS stops.
Anything else in the log?

**Comment by androidAppGuard** [comment]
I reproduced it and it is the full log of the last click.

```
05-18 02:21:44.318 3835-3835/com.svox.pico A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x7f60d474b970 in tid 3835 (com.svox.pico)
05-18 02:21:44.318 4244-4244/org.runnerup.debug E/TrackerComponentCollection: GPS onEnd => RESULT_OK
05-18 02:21:44.318 4244-4244/org.runnerup.debug E/TrackerComponentCollection: Cadence onEnd => RESULT_OK
05-18 02:21:44.318 4244-4244/org.runnerup.debug E/TrackerComponentCollection: WEAR onEnd => RESULT_OK
05-18 02:21:44.318 4244-4244/org.runnerup.debug E/ActivityThread: Failed to find provider info for com.getpebble.android.provider.basalt
05-18 02:21:44.319 4244-4244/org.runnerup.debug E/ActivityThread: Failed to find provider info for com.getpebble.android.provider
05-18 02:21:44.319 4244-4244/org.runnerup.debug E/TrackerComponentCollection: PEBBLE onEnd => RESULT_OK
05-18 02:21:44.319 4244-4244/org.runnerup.debug E/TrackerComponentCollection: HRM onEnd => RESULT_OK
05-18 02:21:44.319 4244-4244/org.runnerup.debug E/TrackerComponentCollection: Receiver onEnd => RESULT_OK
05-18 02:21:44.319 4244-4244/org.runnerup.debug E/TrackerComponentCollection: Temperature onEnd => RESULT_OK
05-18 02:21:44.319 4244-4244/org.runnerup.debug E/TrackerComponentCollection:  => return directly
05-18 02:21:44.329 10218-10261/? D/AudioFlinger: mixer(0xf43c0000) throttle end: throttle time(11)
05-18 02:21:44.357 4244-4263/org.runnerup.debug D/EGL_emulation: eglMakeCurrent: 0x7f5fdfc64820: ver 2 0 (tinfo 0x7f5fdfc459e0)
05-18 02:21:44.361 4244-4263/org.runnerup.debug D/EGL_emulation: eglMakeCurrent: 0x7f5fdfc64820: ver 2 0 (tinfo 0x7f5fdfc459e0)
05-18 02:21:44.362 4244-4244/org.runnerup.debug E/TrackerComponentCollection: Pressure onInit => RESULT_OK
05-18 02:21:44.363 4244-4244/org.runnerup.debug I/TextToSpeech: Sucessfully bound to com.svox.pico
05-18 02:21:44.363 4244-4244/org.runnerup.debug E/TrackerComponentCollection: TTS onInit => RESULT_PENDING
05-18 02:21:44.363 4244-4244/org.runnerup.debug E/TrackerComponentCollection: Elevation onInit => RESULT_OK
05-18 02:21:44.363 4244-4244/org.runnerup.debug E/TrackerComponentCollection: GPS onInit => RESULT_OK
05-18 02:21:44.363 4244-4244/org.runnerup.debug E/TrackerComponentCollection: Cadence onInit => RESULT_OK
05-18 02:21:44.364 4244-4244/org.runnerup.debug E/TrackerComponentCollection: WEAR onInit => RESULT_NOT_SUPPORTED
05-18 02:21:44.364 4244-4244/org.runnerup.debug E/ActivityThread: Failed to find provider info for com.getpebble.android.provider.basalt
05-18 02:21:44.365 4244-4244/org.runnerup.debug E/ActivityThread: Failed to find provider info for com.getpebble.android.provider
05-18 02:21:44.365 4244-4244/org.runnerup.debug E/TrackerComponentCollection: PEBBLE onInit => RESULT_NOT_SUPPORTED
05-18 02:21:44.365 4244-4244/org.runnerup.debug E/TrackerComponentCollection: HRM onInit => RESULT_UNKNOWN
05-18 02:21:44.365 4244-4244/org.runnerup.debug E/TrackerComponentCollection: Receiver onInit => RESULT_OK
05-18 02:21:44.365 4244-4244/org.runnerup.debug E/TrackerComponentCollection: Temperature onInit => RESULT_OK
05-18 02:21:44.366 10523-10638/system_process W/ActivityManager: Bad activity token: android.os.BinderProxy@4b408cb
    java.lang.ClassCastException: android.os.BinderProxy cannot be cast to com.android.server.am.ActivityRecord$Token
        at com.android.server.am.ActivityRecord.forTokenLocked(ActivityRecord.java:424)
        at com.android.server.am.ActivityRecord.isInStackLocked(ActivityRecord.java:1121)
        at com.android.server.am.ActivityManagerService.getActivityOptions(ActivityManagerService.java:11038)
        at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:1734)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2443)
        at android.os.Binder.execTransact(Binder.java:453)
05-18 02:21:44.368 4244-4263/org.runnerup.debug D/EGL_emulation: eglMakeCurrent: 0x7f5fdfc64820: ver 2 0 (tinfo 0x7f5fdfc459e0)
05-18 02:21:44.378 4244-4263/org.runnerup.debug D/EGL_emulation: eglMakeCurrent: 0x7f5fdfc64820: ver 2 0 (tinfo 0x7f5fdfc459e0)
05-18 02:21:44.381 4244-4263/org.runnerup.debug D/EGL_emulation: eglMakeCurrent: 0x7f5fdfc64820: ver 2 0 (tinfo 0x7f5fdfc459e0)
05-18 02:21:44.387 4244-4263/org.runnerup.debug D/EGL_emulation: eglMakeCurrent: 0x7f5fdfc64820: ver 2 0 (tinfo 0x7f5fdfc459e0)
05-18 02:21:44.393 4244-4263/org.runnerup.debug D/EGL_emulation: eglMakeCurrent: 0x7f5fdfc64820: ver 2 0 (tinfo 0x7f5fdfc459e0)
05-18 02:21:44.397 4244-4263/org.runnerup.debug D/EGL_emulation: eglMakeCurrent: 0x7f5fdfc64820: ver 2 0 (tinfo 0x7f5fdfc459e0)
05-18 02:21:44.405 4244-4263/org.runnerup.debug D/EGL_emulation: eglMakeCurrent: 0x7f5fdfc64820: ver 2 0 (tinfo 0x7f5fdfc459e0)
05-18 02:21:44.409 4244-4263/org.runnerup.debug D/EGL_emulation: eglMakeCurrent: 0x7f5fdfc64820: ver 2 0 (tinfo 0x7f5fdfc459e0)
05-18 02:21:44.410 4244-4263/org.runnerup.debug E/Surface: getSlotFromBufferLocked: unknown buffer: 0x7f5fdfc66620
05-18 02:21:44.426 1731-1731/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-18 02:21:44.426 1731-1731/? A/DEBUG: Build fingerprint: 'Android/sdk_google_phone_x86_64/generic_x86_64:6.0/MASTER/6695544:userdebug/test-keys'
05-18 02:21:44.426 1731-1731/? A/DEBUG: Revision: '0'
05-18 02:21:44.426 1731-1731/? A/DEBUG: ABI: 'x86_64'
05-18 02:21:44.426 1731-1731/? A/DEBUG: pid: 3835, tid: 3835, name: com.svox.pico  >>> com.svox.pico <<<
05-18 02:21:44.426 1731-1731/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x7f60d474b970
05-18 02:21:44.431 1731-1731/? A/DEBUG:     rax 00007f5fd474b970  rbx 00007f5fd4749028  rcx 00007f60d474b970  rdx 00007f5fd4749200
05-18 02:21:44.431 1731-1731/? A/DEBUG:     rsi 00007f5fd4749098  rdi 00007f5fd4661408
05-18 02:21:44.431 1731-1731/? A/DEBUG:     r8  0000000000002770  r9  0000000100000000  r10 0000000000000004  r11 0000000000000246
05-18 02:21:44.431 1731-1731/? A/DEBUG:     r12 00007f5fd4661408  r13 00007f5fd4662b70  r14 0000000012c87040  r15 0000000070bf9c40
05-18 02:21:44.431 1731-1731/? A/DEBUG:     cs  0000000000000033  ss  000000000000002b
05-18 02:21:44.431 1731-1731/? A/DEBUG:     rip 00007f5fe400062f  rbp 00007f5fd4746d10  rsp 00007fff0e865d28  eflags 0000000000010202
05-18 02:21:44.443 1731-1731/? A/DEBUG: backtrace:
05-18 02:21:44.443 1731-1731/? A/DEBUG:     #00 pc 000000000001462f  /system/lib64/libttspico.so (picoos_deallocate+47)
05-18 02:21:44.443 1731-1731/? A/DEBUG:     #01 pc 0000000000034084  /system/lib64/libttspico.so (sigDeallocate+292)
05-18 02:21:44.443 1731-1731/? A/DEBUG:     #02 pc 0000000000032726  /system/lib64/libttspico.so
05-18 02:21:44.443 1731-1731/? A/DEBUG:     #03 pc 0000000000012f93  /system/lib64/libttspico.so (picodata_disposeProcessingUnit+35)
05-18 02:21:44.443 1731-1731/? A/DEBUG:     #04 pc 0000000000011909  /system/lib64/libttspico.so
05-18 02:21:44.443 1731-1731/? A/DEBUG:     #05 pc 0000000000012f93  /system/lib64/libttspico.so (picodata_disposeProcessingUnit+35)
05-18 02:21:44.443 1731-1731/? A/DEBUG:     #06 pc 0000000000012584  /system/lib64/libttspico.so (picoctrl_disposeEngine+68)
05-18 02:21:44.443 1731-1731/? A/DEBUG:     #07 pc 0000000000011337  /system/lib64/libttspico.so (pico_disposeEngine+71)
05-18 02:21:44.443 1731-1731/? A/DEBUG:     #08 pc 000000000000c015  /system/lib64/libttspico.so (android::TtsEngine::shutdown()+37)
05-18 02:21:44.443 1731-1731/? A/DEBUG:     #09 pc 0000000000001b92  /system/lib64/libttscompat.so
05-18 02:21:44.443 1731-1731/? A/DEBUG:     #10 pc 0000000000009139  /system/app/PicoTts/oat/x86_64/PicoTts.odex (offset 0x8000)
05-18 02:21:44.534 1731-1731/? A/DEBUG: Tombstone written to: /data/tombstones/tombstone_00
05-18 02:21:44.534 1731-1731/? E/DEBUG: AM write failed: Broken pipe
05-18 02:21:44.536 10523-10543/system_process I/BootReceiver: Copying /data/tombstones/tombstone_00 to DropBox (SYSTEM_TOMBSTONE)
05-18 02:21:44.553 10523-11877/system_process I/AccountManagerService: getTypesVisibleToCaller: isPermitted? true
05-18 02:21:44.555 10523-11139/system_process I/AccountManagerService: getTypesVisibleToCaller: isPermitted? true
05-18 02:21:44.562 10523-10585/system_process I/OpenGLRenderer: Initialized EGL, version 1.4
05-18 02:21:44.570 10523-10585/system_process D/EGL_emulation: eglCreateContext: 0x7f5fdb95f880: maj 2 min 0 rcv 2
05-18 02:21:44.591 10219-10219/? I/Zygote: Process 3835 exited due to signal (11)
05-18 02:21:44.591 10523-10973/system_process I/ActivityManager: Process com.svox.pico (pid 3835) has died
05-18 02:21:44.592 10523-10973/system_process W/ActivityManager: Scheduling restart of crashed service com.svox.pico/.PicoService in 1000ms
05-18 02:21:44.595 10523-10585/system_process D/EGL_emulation: eglMakeCurrent: 0x7f5fdb95f880: ver 2 0 (tinfo 0x7f5fd27ff580)
05-18 02:21:44.601 10523-10585/system_process D/EGL_emulation: eglMakeCurrent: 0x7f5fdb95f880: ver 2 0 (tinfo 0x7f5fd27ff580)
05-18 02:21:44.681 4244-4263/org.runnerup.debug D/EGL_emulation: eglMakeCurrent: 0x7f5fdfc64820: ver 2 0 (tinfo 0x7f5fdfc459e0)
05-18 02:21:45.603 10523-10540/system_process I/ActivityManager: Start proc 4377:com.svox.pico/u0a45 for service com.svox.pico/.PicoService
05-18 02:21:45.610 4377-4377/com.svox.pico V/SynthProxy: About to load libttspico.so, applyFilter=true
05-18 02:21:45.615 4377-4377/com.svox.pico I/SVOX Pico Engine: loaded en-US successfully
05-18 02:21:45.617 4244-4244/org.runnerup.debug I/TextToSpeech: Connected to ComponentInfo{com.svox.pico/com.svox.pico.PicoService}
05-18 02:21:45.618 4244-4268/org.runnerup.debug I/TextToSpeech: Set up connection to ComponentInfo{com.svox.pico/com.svox.pico.PicoService}
05-18 02:21:45.618 4244-4244/org.runnerup.debug E/TrackerComponentCollection: TTS onInit => RESULT_OK
05-18 02:21:45.618 4244-4244/org.runnerup.debug E/TrackerComponentCollection:  => runCallback()
05-18 02:21:45.618 4244-4244/org.runnerup.debug E/org.runnerup.tracker.Tracker$1: state.set(INITIALIZED)
05-18 02:21:46.308 4244-4263/org.runnerup.debug E/Surface: getSlotFromBufferLocked: unknown buffer: 0x7f5fe5825940
05-18 02:21:46.331 4244-4263/org.runnerup.debug D/EGL_emulation: eglMakeCurrent: 0x7f5fdfc64820: ver 2 0 (tinfo 0x7f5fdfc459e0)
05-18 02:21:47.449 10218-10261/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 2157733565 , only wrote 2157596540
05-18 02:21:48.311 4244-4263/org.runnerup.debug D/EGL_emulation: eglMakeCurrent: 0x7f5fdfc64820: ver 2 0 (tinfo 0x7f5fdfc459e0)
05-18 02:21:48.312 4244-4263/org.runnerup.debug E/Surface: getSlotFromBufferLocked: unknown buffer: 0x7f5fe58247c0
05-18 02:21:48.351 4244-4263/org.runnerup.debug D/EGL_emulation: eglMakeCurrent: 0x7f5fdfc64820: ver 2 0 (tinfo 0x7f5fdfc459e0)
05-18 02:21:50.312 4244-4263/org.runnerup.debug D/EGL_emulation: eglMakeCurrent: 0x7f5fdfc64820: ver 2 0 (tinfo 0x7f5fdfc459e0)
05-18 02:21:50.313 4244-4263/org.runnerup.debug E/Surface: getSlotFromBufferLocked: unknown buffer: 0x7f5fdfc66620
05-18 02:21:50.347 4244-4263/org.runnerup.debug D/EGL_emulation: eglMakeCurrent: 0x7f5fdfc64820: ver 2 0 (tinfo 0x7f5fdfc459e0)
05-18 02:21:52.312 4244-4263/org.runnerup.debug D/EGL_emulation: eglMakeCurrent: 0x7f5fdfc64820: ver 2 0 (tinfo 0x7f5fdfc459e0)
05-18 02:21:52.313 4244-4263/org.runnerup.debug E/Surface: getSlotFromBufferLocked: unknown buffer: 0x7f5fe5825940
05-18 02:21:57.084 10523-11199/system_process I/AccountManagerService: getTypesVisibleToCaller: isPermitted? true
05-18 02:22:20.060 1284-1338/? D/hwcomposer: hw_composer sent 742 syncs in 66s
```

**Comment by androidAppGuard** [comment]
Is the app crashing because of PicoTTS？

**Comment by gerhardol** [comment]
> 05-18 02:21:44.318 3835-3835/com.svox.pico A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x7f60d474b970 in tid 3835 (com.svox.pico)

PicoTTS dies first. I have not seen a way to prevent the app from crash due to this, there is nothing about when the tts is used.
So if a check (or try-catch) of the tts object is required in one or many situations is unknown.
