### ISSUE TITLE
formatHeartrate(CUE) gives exception

### ISSUE THREAD

**Issue by jonasoreland** [jonasoreland/runnerup#187]
Settings=>Audio cues
Check lap heartrate
Press Push

    android.content.res.Resources$NotFoundException: Plural resource ID #0xa1 quantity=2131230726 item=other
            at android.content.res.Resources.getQuantityText(Resources.java:1474)
            at android.content.res.Resources.getQuantityString(Resources.java:1617)
            at org.runnerup.util.Formatter.formatHeartRate(Formatter.java:261)
            at org.runnerup.util.Formatter.format(Formatter.java:150)
            at org.runnerup.workout.feedback.AudioFeedback.getCue(AudioFeedback.java:104)
            at org.runnerup.workout.feedback.AudioFeedback.emit(AudioFeedback.java:112)
            at org.runnerup.view.AudioCueSettingsActivity$8$1.onInit(AudioCueSettingsActivity.java:408)
            at org.runnerup.view.AudioCueSettingsActivity$8.onPreferenceClick(AudioCueSettingsActivity.java:429)
            at android.preference.Preference.performClick(Preference.java:1054)
            at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:229)

**Comment by paradix** [comment]
I noticed during my latest workout that the HR cue was missing, but code-wise it looks fine, at least at first glance.

**Comment by jonasoreland** [comment]
maybe a bug in resource compiler...
or the shrinkResources (but I don't I use that...as I do debug build).

maybe we should move all the plurals into cues.xml
and remove those not used...

/Jonas

**Comment by paradix** [comment]
What language cases the exception for you?

**Comment by jonasoreland** [comment]
english

**Comment by paradix** [comment]
Maybe this: http://stackoverflow.com/questions/6677716/using-plurals-ends-in-resourcesnotfoundexception

**Comment by jonasoreland** [comment]
yea, i saw that too....and that's pretty bad...
almost to the point of abandoning android plurals...or wdyt ??

/Jonas

**Comment by paradix** [comment]
But that's pretty weird. It worked and suddenly started throwing exceptions.
I even tried to build some old version of the app where the plurals were introduced and even this one is causing the same problem.

**Comment by paradix** [comment]
maybe this way? http://stackoverflow.com/questions/12751622/how-to-make-russian-quantity-strings-work-properly

**Comment by paradix** [comment]
I'm clueless. I have inspected the build apk file and everything seems fine there. All plurals are right there only once. Nothing suspicious there, so no idea what's causing this. 
Could this be debugged deeper with android code? Is this possible?

**Comment by paradix** [comment]
Hahaha there is a stupid but it the Formatter. 
The arguments for getQuantityString Method inf Formatter.formatHeartRate have the arguments switched. 
It is: 
```
resources.getQuantityString((int)heart_rate, R.plurals.cue_bpm);

It schoul be:
```
resources.getQuantityString(R.plurals.cue_bpm, (int)heart_rate);
