### ISSUE TITLE
Crash when opening activity downloaded from runkeeper 

### ISSUE THREAD

**Issue by nebmo** [jonasoreland/runnerup#239]
I haven't debugged this yet but it happens for 1 in 10 of the downloaded activities when clicking on them from history list

**Comment by paradix** [comment]
Do you think you could post the log, from CatLog for example?

**Comment by nebmo** [comment]
Didnt really find any interesting log. only thing i found was this:
04-22 11:24:02.814    9454-9678/? E/AndroidRuntime﹕ FATAL EXCEPTION: ZoomTableManager
    Process: org.runnerup, PID: 9454
    java.lang.IllegalMonitorStateException: object not locked by thread before notifyAll()
            at java.lang.Object.notifyAll(Native Method)
            at com.google.maps.api.android.lib6.gmm6.m.k.a(Unknown Source)
            at com.google.maps.api.android.lib6.gmm6.m.l.run(Unknown Source)

I wonder if is error is because I build the apk myself without a google maps api key?

**Comment by paradix** [comment]
maybe you could debug it than? I didn't notice any problems while developing and testing but it's probable that I did implement some bugs ;)

**Comment by ixeft** [comment]
I'm experimenting the same bug,
I noticed that it append only with my oldest workout,
and I think I was using the official RunKeeper at the time.

Maybe you can reproduce the bug this way !

**Comment by paradix** [comment]
Can one of you guys produce a log for this (debug or catLog)?

**Comment by ixeft** [comment]
Hello,

Here is the error when opening the activity.
 
 06-14 21:31:20.486      840-969/? I/ServiceKeeper﹕ In getpackagename pid = 840 uid = 1000 package name = android
  06-14 21:31:20.486  10241-21648/org.runnerup W/dalvikvm﹕ threadid=26: thread exiting with uncaught exception (group=0x4186cda0)
  06-14 21:31:20.496  10241-21648/org.runnerup E/AndroidRuntime﹕ FATAL EXCEPTION: AsyncTask  #3
    Process: org.runnerup, PID: 10241
    java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.os.AsyncTask$3.done(AsyncTask.java:300)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
     Caused by: java.lang.NullPointerException
            at org.runnerup.view.DetailActivity$11.doInBackground(DetailActivity.java:1282)
            at org.runnerup.view.DetailActivity$11.doInBackground(DetailActivity.java:1200)
            at android.os.AsyncTask$2.call(AsyncTask.java:288)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)

**Comment by jonasoreland** [comment]
does this still happen also wtih latest fixes ??
- do you build yourself or shall I make another beta

/Jonas

**Comment by paradix** [comment]
I'm investigating, but I can't find any activity of mine that has this problem.
I can build in an if statement, but I can't test it properly.

**Comment by paradix** [comment]
I really don't know how this problem can occur. The NPE comes from lastLocation beeing null.
This can occur only when there is no START point in the activity.

**Comment by ixeft** [comment]
Problem indeed solved !
 thanks @paradix

**Comment by jonasoreland** [comment]
doesn't that sound like there is a bug in the code importing from runkeeper
??

/Jonas

**Comment by nebmo** [comment]
For me it has crashed on activities not downloaded from runkeeper

**Comment by jonasoreland** [comment]
but...this is ancient code, isn't it ??

can you send a db.export which makes (made) it crash ??

/Jonas

**Comment by nebmo** [comment]
It's really strange.. I can't reproduce it now. But now I'm using official release so I think the crashes I had before was related to maps and missing key.

**Comment by jonasoreland** [comment]
> I really don't know how this problem can occur. The NPE comes from
lastLocation beeing null.
> This can occur only when there is no START point in the activity.
so then I repeat my statement: doesn't that sound like there is a bug in
the code importing from runkeeper ??

**Comment by paradix** [comment]
Well I'm not sure about this. When downloading the activity the type of the point is set based on the data retrieved from runkeeper. I would have to change the data to make it work (i.e. if the first point != START change to START).

But it would be a lot easier to check with such an activity in my database.

**Comment by jonasoreland** [comment]
you *HAVE TO* modify runkeeper (or any other datasource) data to conform to
runnerup consistency rules.
the import function shall produce the "best equivalent" representation of
source data. that does not have to be an exact copy.

see what I mean ?

/Jonas

**Comment by ixeft** [comment]
I will try to export my database tonight so you can test with data ;)

**Comment by paradix** [comment]
Ok than, this should not be any problem. I'll have a look and commit the changes.
