### ISSUE TITLE
Bug: Widget added to master doesn't work on froyo

### ISSUE THREAD

**Issue by daverix** [jonasoreland/runnerup#324]
It uses APIs that doesn't exist in froyo... Either the widget should be latest flavor only or the widget should use apis supported on froyo...

```
09-19 13:53:24.911 1208-1208/org.runnerup E/dalvikvm: Could not find class 'org.runnerup.feedwidget.FeedWidgetService', referenced from method org.runnerup.feedwidget.FeedWidgetProvider.onUpdate
09-19 13:53:24.931 1208-1208/org.runnerup E/AndroidRuntime: FATAL EXCEPTION: main
09-19 13:53:24.931 1208-1208/org.runnerup E/AndroidRuntime: java.lang.NoClassDefFoundError: org.runnerup.feedwidget.FeedWidgetService
09-19 13:53:24.931 1208-1208/org.runnerup E/AndroidRuntime:     at org.runnerup.feedwidget.FeedWidgetProvider.onUpdate(FeedWidgetProvider.java:84)
09-19 13:53:24.931 1208-1208/org.runnerup E/AndroidRuntime:     at org.runnerup.feedwidget.FeedWidgetProvider.onReceive(FeedWidgetProvider.java:74)
09-19 13:53:24.931 1208-1208/org.runnerup E/AndroidRuntime:     at android.app.ActivityThread.handleReceiver(ActivityThread.java:1794)
09-19 13:53:24.931 1208-1208/org.runnerup E/AndroidRuntime:     at android.app.ActivityThread.access$2400(ActivityThread.java:117)
09-19 13:53:24.931 1208-1208/org.runnerup E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:981)
09-19 13:53:24.931 1208-1208/org.runnerup E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:99)
09-19 13:53:24.931 1208-1208/org.runnerup E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:130)
09-19 13:53:24.931 1208-1208/org.runnerup E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:3683)
09-19 13:53:24.931 1208-1208/org.runnerup E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
09-19 13:53:24.931 1208-1208/org.runnerup E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:507)
09-19 13:53:24.931 1208-1208/org.runnerup E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
09-19 13:53:24.931 1208-1208/org.runnerup E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
09-19 13:53:24.931 1208-1208/org.runnerup E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)
```

**Comment by bagage** [comment]
When I'm choosing build variant FroyoDebug and press "Run" button, everything goes fine. Can you describe me how do you get errors within Android Studio so that I can reproduce it please? Thanks!

(continuing here instead of #309 )

**Comment by daverix** [comment]
I'm adding a widget...

**Comment by jonasoreland** [comment]
this is fixed now, right ?

**Comment by bagage** [comment]
it should be yes.
