### ISSUE TITLE
Polar HRM (2008, H7) support

### ISSUE THREAD

**Issue by tbdal** [jonasoreland/runnerup#334]
Hi Jonas,

thanks for your encredible efforts!

RunnerUp is not able to connect to HRM Monitor by polar from 2008 (called H7?)

Should this HRM work by selecting "Polar WearLink" -> name: Polar iWL ?

Thanks a lot for looking into this, attached you'll find a screenshot of RunnerUp. Can I give you access to logs/debugs in any way?

cheers,
tbdal
![screenshot_2015-09-29-21-10-23](https://cloud.githubusercontent.com/assets/6881189/10175519/9673ef6e-66ef-11e5-910d-fcb1ca70dc7b.jpg)

![Uploading Screenshot_2015-09-29-21-10-23.jpg…]()

**Comment by tbdal** [comment]
i compiled the app. adb shows the following:

09-29 21:41:08.130    6811-6811/? I/art﹕ Late-enabling -Xcheck:jni
09-29 21:41:08.148    6811-6821/? I/art﹕ Debugger is no longer active
09-29 21:41:08.248    6811-6811/? E/org.runnerup.view.MainLayout﹕ app-version: 8000050, upgradeState: SAME, km: true
09-29 21:41:08.252    6811-6811/? W/Resources﹕ Converting to string: TypedValue{t=0x10/d=0x78 a=-1}
09-29 21:41:08.255    6811-6811/? W/Resources﹕ Converting to string: TypedValue{t=0x10/d=0x3e8 a=-1}
09-29 21:41:08.297    6811-6811/? E/org.runnerup.view.MainLayout﹕ Found: /data/data/org.runnerup/files/.., app_workouts, isFile: false
09-29 21:41:08.324    6811-6811/? E/org.runnerup.view.MainLayout﹕ Found: /data/data/org.runnerup/files/../app_workouts, 8-6-4-2.json, isFile: true
09-29 21:41:08.324    6811-6811/? E/org.runnerup.view.MainLayout﹕ Skip: /data/data/org.runnerup/files/../app_workouts/8-6-4-2.json, isDirectory(): false, isFile(): true
09-29 21:41:08.324    6811-6811/? E/org.runnerup.view.MainLayout﹕ Found: /data/data/org.runnerup/files/../app_workouts, MalinEwerlov.json, isFile: true
09-29 21:41:08.324    6811-6811/? E/org.runnerup.view.MainLayout﹕ Skip: /data/data/org.runnerup/files/../app_workouts/MalinEwerlov.json, isDirectory(): false, isFile(): true
09-29 21:41:08.324    6811-6811/? E/org.runnerup.view.MainLayout﹕ Found: /data/data/org.runnerup/files/../app_workouts, Super1000.json, isFile: true
09-29 21:41:08.325    6811-6811/? E/org.runnerup.view.MainLayout﹕ Skip: /data/data/org.runnerup/files/../app_workouts/Super1000.json, isDirectory(): false, isFile(): true
09-29 21:41:08.325    6811-6811/? E/org.runnerup.view.MainLayout﹕ Found: /data/data/org.runnerup/files/.., shared_prefs, isFile: false
09-29 21:41:08.351    6811-6811/? E/org.runnerup.view.MainLayout﹕ Found: /data/data/org.runnerup/files/../shared_prefs, 100m_audio_cues.xml, isFile: true
09-29 21:41:08.351    6811-6811/? E/org.runnerup.view.MainLayout﹕ Skip: /data/data/org.runnerup/files/../shared_prefs/100m_audio_cues.xml, isDirectory(): false, isFile(): true
09-29 21:41:08.358    6811-6834/? D/OpenGLRenderer﹕ Use EGL_SWAP_BEHAVIOR_PRESERVED: true
09-29 21:41:08.368    6811-6811/? D/Atlas﹕ Validating map...
09-29 21:41:08.451    6811-6811/? W/Resources﹕ Converting to string: TypedValue{t=0x10/d=0x3e8 a=-1}
09-29 21:41:08.466    6811-6811/? W/Resources﹕ Converting to string: TypedValue{t=0x10/d=0xc8 a=-1}
09-29 21:41:08.475    6811-6811/? W/Resources﹕ Converting to string: TypedValue{t=0x10/d=0x5 a=-1}
09-29 21:41:08.665    6811-6826/? I/art﹕ Background sticky concurrent mark sweep GC freed 12464(880KB) AllocSpace objects, 7(110KB) LOS objects, 8% free, 11MB/12MB, paused 19.457ms total 53.354ms
09-29 21:41:08.767    6811-6834/? I/Adreno-EGL﹕ <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_LA.BF.1.1.1_RB1.05.01.00.042.030_msm8974_LA.BF.1.1.1_RB1__release_AU ()
    OpenGL ES Shader Compiler Version: E031.25.03.06
    Build Date: 05/17/15 Sun
    Local Branch: mybranch10089422
    Remote Branch: quic/LA.BF.1.1.1_rb1.22
    Local Patches: NONE
    Reconstruct Branch: AU_LINUX_ANDROID_LA.BF.1.1.1_RB1.05.01.00.042.030 + 6151be1 +  NOTHING
09-29 21:41:08.768    6811-6834/? I/OpenGLRenderer﹕ Initialized EGL, version 1.4
09-29 21:41:08.784    6811-6834/? D/OpenGLRenderer﹕ Enabling debug mode 0
09-29 21:41:08.869    6811-6811/? E/org.runnerup.view.StartFragment﹕ StartActivity.startGps()
09-29 21:41:08.874    6811-6811/? E/org.runnerup.tracker.Tracker﹕ Tracker.connect() - state: INIT
09-29 21:41:08.883    6811-6811/? I/TextToSpeech﹕ Sucessfully bound to com.svox.pico
09-29 21:41:08.883    6811-6811/? E/TrackerComponentCollection﹕ TTS onInit => RESULT_PENDING
09-29 21:41:08.883    6811-6811/? E/TrackerComponentCollection﹕ WEAR onInit => RESULT_NOT_SUPPORTED
09-29 21:41:08.885    6811-6811/? E/TrackerComponentCollection﹕ GPS onInit => RESULT_OK
09-29 21:41:08.885    6811-6811/? E/TrackerComponentCollection﹕ HRM onInit => RESULT_UNKNOWN
09-29 21:41:08.885    6811-6811/? E/TrackerComponentCollection﹕ Receiver onInit => RESULT_OK
09-29 21:41:08.885    6811-6811/? E/org.runnerup.tracker.Tracker﹕ => nextState: CONNECTED
09-29 21:41:08.929    6811-6834/? V/RenderScript﹕ Application requested CPU execution
09-29 21:41:08.936    6811-6834/? V/RenderScript﹕ 0xa22d1e00 Launching thread(s), CPUs 4
09-29 21:41:08.947    6811-6811/? I/TextToSpeech﹕ Connected to ComponentInfo{com.svox.pico/com.svox.pico.PicoService}
09-29 21:41:08.948    6811-6811/? I/Timeline﹕ Timeline: Activity_idle id: android.os.BinderProxy@22e67b1e time:20050979
09-29 21:41:08.952    6811-6852/? I/TextToSpeech﹕ Set up connection to ComponentInfo{com.svox.pico/com.svox.pico.PicoService}
09-29 21:41:08.953    6811-6811/? E/TrackerComponentCollection﹕ TTS onInit => RESULT_OK
09-29 21:41:08.953    6811-6811/? E/TrackerComponentCollection﹕ => runCallback()
09-29 21:41:08.953    6811-6811/? E/org.runnerup.tracker.Tracker$1﹕ state.set(INITIALIZED)
09-29 21:41:08.953    6811-6811/? E/org.runnerup.tracker.Tracker﹕ Tracker.connect() - state: INITIALIZED
09-29 21:41:08.971    6811-6811/? E/TrackerComponentCollection﹕ WEAR onConnecting => RESULT_NOT_SUPPORTED
09-29 21:41:08.971    6811-6811/? E/TrackerComponentCollection﹕ TTS onConnecting => RESULT_OK
09-29 21:41:08.976    6811-6811/? E/TrackerComponentCollection﹕ GPS onConnecting => RESULT_PENDING
09-29 21:41:08.976    6811-6811/? E/TrackerComponentCollection﹕ HRM onConnecting => RESULT_NOT_SUPPORTED
09-29 21:41:08.976    6811-6811/? E/TrackerComponentCollection﹕ Receiver onConnecting => RESULT_OK
09-29 21:41:13.419    6811-6811/org.runnerup W/Resources﹕ Converting to string: TypedValue{t=0x10/d=0x3e8 a=-1}
09-29 21:41:13.422    6811-6811/org.runnerup W/Resources﹕ Converting to string: TypedValue{t=0x10/d=0xf a=-1}
09-29 21:41:13.426    6811-6811/org.runnerup W/Resources﹕ Converting to string: TypedValue{t=0x10/d=0x3 a=-1}
09-29 21:41:13.427    6811-6811/org.runnerup W/Resources﹕ Converting to string: TypedValue{t=0x10/d=0x3c a=-1}
09-29 21:41:13.432    6811-6811/org.runnerup W/Resources﹕ Converting to string: TypedValue{t=0x10/d=0xf a=-1}
09-29 21:41:13.436    6811-6811/org.runnerup W/Resources﹕ Converting to string: TypedValue{t=0x10/d=0x1f4 a=-1}
09-29 21:41:13.437    6811-6811/org.runnerup W/Resources﹕ Converting to string: TypedValue{t=0x10/d=0x0 a=-1}
09-29 21:41:13.439    6811-6811/org.runnerup W/Resources﹕ Converting to string: TypedValue{t=0x10/d=0xf a=-1}
09-29 21:41:13.440    6811-6811/org.runnerup W/Resources﹕ Converting to string: TypedValue{t=0x10/d=0x4b a=-1}
09-29 21:41:13.900    6811-6811/org.runnerup E/org.runnerup.view.StartFragment﹕ StartActivity.stopGps() skipStop: false
09-29 21:41:13.903    6811-6811/org.runnerup E/TrackerComponentCollection﹕ WEAR onEnd => RESULT_OK
09-29 21:41:13.907    6811-6811/org.runnerup E/TrackerComponentCollection﹕ TTS onEnd => RESULT_OK
09-29 21:41:13.909    6811-6811/org.runnerup E/TrackerComponentCollection﹕ GPS onEnd => RESULT_OK
09-29 21:41:13.909    6811-6811/org.runnerup E/TrackerComponentCollection﹕ HRM onEnd => RESULT_OK
09-29 21:41:13.910    6811-6811/org.runnerup E/TrackerComponentCollection﹕ Receiver onEnd => RESULT_OK
09-29 21:41:13.910    6811-6811/org.runnerup E/TrackerComponentCollection﹕ => return directly
09-29 21:41:13.913    6811-6811/org.runnerup E/org.runnerup.view.StartFragment﹕ StartActivity.stopGps() skipStop: false
09-29 21:41:14.752    6811-6811/org.runnerup I/Timeline﹕ Timeline: Activity_launch_request id:org.runnerup time:20056783
09-29 21:41:14.804    6811-6811/org.runnerup I/art﹕ Rejecting re-init on previously-failed class java.lang.Class<org.runnerup.hr.SamsungBLEHRProvider$2>
09-29 21:41:14.804    6811-6811/org.runnerup I/art﹕ Rejecting re-init on previously-failed class java.lang.Class<org.runnerup.hr.SamsungBLEHRProvider$2>
09-29 21:41:14.833    6811-6811/org.runnerup E/org.runnerup.view.HRSettingsActivity﹕ btName: null
09-29 21:41:14.833    6811-6811/org.runnerup E/org.runnerup.view.HRSettingsActivity﹕ btAddress: null
09-29 21:41:14.833    6811-6811/org.runnerup E/org.runnerup.view.HRSettingsActivity﹕ btProviderName: null
09-29 21:41:14.915    6811-6834/org.runnerup D/OpenGLRenderer﹕ endAllStagingAnimators on 0xa2202380 (ListView) with handle 0xa201a7a0
09-29 21:41:14.923    6811-6811/org.runnerup I/Timeline﹕ Timeline: Activity_idle id: android.os.BinderProxy@11e87773 time:20056954
09-29 21:41:18.389    6811-6811/org.runnerup W/System.err﹕ getHRProvider(Polar WearLink)
09-29 21:41:19.069    6811-6811/org.runnerup W/System.err﹕ [ RetryingHRProviderProxy: Polar WearLink, attempt: 0 ], state: OPENING, request: OPENED, onOpenResult(true)
09-29 21:41:20.860    6811-6811/org.runnerup W/System.err﹕ [ RetryingHRProviderProxy: Polar WearLink, attempt: 0 ], state: OPENED, request: OPENED, connect(org.runnerup.hr.HRDeviceRef@3a713da8)
09-29 21:41:20.878    6811-7064/org.runnerup W/BluetoothAdapter﹕ getBluetoothService() called with no BluetoothManagerCallback
09-29 21:41:20.898    6811-6811/org.runnerup W/System.err﹕ [ RetryingHRProviderProxy: Polar WearLink, attempt: 0 ], state: CONNECTING, request: CONNECTED, tryConnect(method: 0)
09-29 21:41:26.049    6811-6811/org.runnerup W/System.err﹕ [ RetryingHRProviderProxy: Polar WearLink, attempt: 0 ], state: CONNECTING, request: CONNECTED, closeSocket
09-29 21:41:26.056    6811-7064/org.runnerup W/System.err﹕ java.io.IOException: read failed, socket might closed or timeout, read ret: -1
09-29 21:41:26.056    6811-7064/org.runnerup W/System.err﹕ at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:573)
09-29 21:41:26.056    6811-7064/org.runnerup W/System.err﹕ at android.bluetooth.BluetoothSocket.readInt(BluetoothSocket.java:584)
09-29 21:41:26.057    6811-7064/org.runnerup W/System.err﹕ at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java:321)
09-29 21:41:26.057    6811-7064/org.runnerup W/System.err﹕ at org.runnerup.hr.Bt20Base.tryConnect(Bt20Base.java:356)
09-29 21:41:26.057    6811-7064/org.runnerup W/System.err﹕ at org.runnerup.hr.Bt20Base$ConnectThread.run(Bt20Base.java:392)
09-29 21:41:26.057    6811-7064/org.runnerup W/BluetoothAdapter﹕ getBluetoothService() called with no BluetoothManagerCallback
09-29 21:41:26.080    6811-6811/org.runnerup W/System.err﹕ [ RetryingHRProviderProxy: Polar WearLink, attempt: 0 ], state: CONNECTING, request: CONNECTED, tryConnect(method: 1)
09-29 21:41:29.350    6811-6811/org.runnerup W/System.err﹕ [ RetryingHRProviderProxy: Polar WearLink, attempt: 0 ], state: CONNECTING, request: CONNECTED, connected => android.bluetooth.BluetoothSocket@3fb57066
09-29 21:41:29.719    6811-6811/org.runnerup W/System.err﹕ [ RetryingHRProviderProxy: Polar WearLink, attempt: 0 ], state: CONNECTING, request: CONNECTED, reportConnected(false) mIsConnecting: true, mIsConnected: false, hrClient: org.runnerup.hr.RetryingHRProviderProxy@3d641fa7
09-29 21:41:29.748    6811-6811/org.runnerup W/System.err﹕ [ RetryingHRProviderProxy: Polar WearLink, attempt: 0 ], state: CONNECTING, request: CONNECTED, onConnectResult(false)
09-29 21:41:29.762    6811-6811/org.runnerup W/System.err﹕ [ RetryingHRProviderProxy: Polar WearLink, attempt: 1 ], state: CONNECTING, request: CONNECTED, retry in 0ms
09-29 21:41:29.775    6811-6811/org.runnerup W/System.err﹕ [ RetryingHRProviderProxy: Polar WearLink, attempt: 1 ], state: CONNECTING, request: CONNECTED, retry connect
09-29 21:41:29.788    6811-7238/org.runnerup W/BluetoothAdapter﹕ getBluetoothService() called with no BluetoothManagerCallback
09-29 21:41:29.805    6811-6811/org.runnerup W/System.err﹕ [ RetryingHRProviderProxy: Polar WearLink, attempt: 1 ], state: CONNECTING, request: CONNECTED, tryConnect(method: 0)
09-29 21:41:30.047    6811-6811/org.runnerup W/System.err﹕ [ RetryingHRProviderProxy: Polar WearLink, attempt: 1 ], state: CONNECTING, request: CONNECTED, closeSocket
09-29 21:41:30.047    6811-7238/org.runnerup W/System.err﹕ java.io.IOException: read failed, socket might closed or timeout, read ret: -1
09-29 21:41:30.047    6811-7238/org.runnerup W/System.err﹕ at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:573)
09-29 21:41:30.047    6811-7238/org.runnerup W/System.err﹕ at android.bluetooth.BluetoothSocket.readInt(BluetoothSocket.java:584)
09-29 21:41:30.048    6811-7238/org.runnerup W/System.err﹕ at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java:321)
09-29 21:41:30.048    6811-7238/org.runnerup W/System.err﹕ at org.runnerup.hr.Bt20Base.tryConnect(Bt20Base.java:356)
09-29 21:41:30.048    6811-7238/org.runnerup W/System.err﹕ at org.runnerup.hr.Bt20Base$ConnectThread.run(Bt20Base.java:392)
09-29 21:41:30.048    6811-7238/org.runnerup W/BluetoothAdapter﹕ getBluetoothService() called with no BluetoothManagerCallback
09-29 21:41:30.056    6811-6811/org.runnerup W/System.err﹕ [ RetryingHRProviderProxy: Polar WearLink, attempt: 1 ], state: CONNECTING, request: CONNECTED, tryConnect(method: 1)
09-29 21:41:35.387    6811-7238/org.runnerup W/System.err﹕ java.io.IOException: read failed, socket might closed or timeout, read ret: -1
09-29 21:41:35.388    6811-7238/org.runnerup W/System.err﹕ at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:573)
09-29 21:41:35.388    6811-7238/org.runnerup W/System.err﹕ at android.bluetooth.BluetoothSocket.waitSocketSignal(BluetoothSocket.java:550)
09-29 21:41:35.388    6811-7238/org.runnerup W/System.err﹕ at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java:325)
09-29 21:41:35.388    6811-7238/org.runnerup W/System.err﹕ at org.runnerup.hr.Bt20Base.tryConnect(Bt20Base.java:356)
09-29 21:41:35.402    6811-6811/org.runnerup W/System.err﹕ [ RetryingHRProviderProxy: Polar WearLink, attempt: 1 ], state: CONNECTING, request: CONNECTED, closeSocket
09-29 21:41:35.411    6811-7238/org.runnerup W/System.err﹕ at org.runnerup.hr.Bt20Base$ConnectThread.run(Bt20Base.java:392)
09-29 21:41:35.418    6811-7238/org.runnerup W/BluetoothAdapter﹕ getBluetoothService() called with no BluetoothManagerCallback
09-29 21:41:35.442    6811-6811/org.runnerup W/System.err﹕ [ RetryingHRProviderProxy: Polar WearLink, attempt: 1 ], state: CONNECTING, request: CONNECTED, tryConnect(method: 2)
09-29 21:41:40.606    6811-6811/org.runnerup W/System.err﹕ [ RetryingHRProviderProxy: Polar WearLink, attempt: 1 ], state: CONNECTING, request: CONNECTED, closeSocket
09-29 21:41:40.606    6811-7238/org.runnerup W/System.err﹕ java.io.IOException: read failed, socket might closed or timeout, read ret: -1
09-29 21:41:40.606    6811-7238/org.runnerup W/System.err﹕ at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:573)
09-29 21:41:40.607    6811-7238/org.runnerup W/System.err﹕ at android.bluetooth.BluetoothSocket.waitSocketSignal(BluetoothSocket.java:550)
09-29 21:41:40.607    6811-7238/org.runnerup W/System.err﹕ at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java:325)
09-29 21:41:40.607    6811-7238/org.runnerup W/System.err﹕ at org.runnerup.hr.Bt20Base.tryConnect(Bt20Base.java:356)
09-29 21:41:40.607    6811-7238/org.runnerup W/System.err﹕ at org.runnerup.hr.Bt20Base$ConnectThread.run(Bt20Base.java:392)
09-29 21:41:40.631    6811-6811/org.runnerup W/System.err﹕ [ RetryingHRProviderProxy: Polar WearLink, attempt: 1 ], state: CONNECTING, request: CONNECTED, connect failed!
09-29 21:41:40.641    6811-6811/org.runnerup W/System.err﹕ [ RetryingHRProviderProxy: Polar WearLink, attempt: 1 ], state: CONNECTING, request: CONNECTED, reportConnected(false) mIsConnecting: true, mIsConnected: false, hrClient: org.runnerup.hr.RetryingHRProviderProxy@3d641fa7
09-29 21:41:40.647    6811-6811/org.runnerup W/System.err﹕ [ RetryingHRProviderProxy: Polar WearLink, attempt: 1 ], state: CONNECTING, request: CONNECTED, onConnectResult(false)
09-29 21:41:40.655    6811-6811/org.runnerup W/System.err﹕ [ RetryingHRProviderProxy: Polar WearLink, attempt: 2 ], state: CONNECTING, request: CONNECTED, retry in 750ms
09-29 21:41:41.413    6811-6811/org.runnerup W/System.err﹕ [ RetryingHRProviderProxy: Polar WearLink, attempt: 2 ], state: CONNECTING, request: CONNECTED, retry connect
09-29 21:41:41.464    6811-7463/org.runnerup W/BluetoothAdapter﹕ getBluetoothService() called with no BluetoothManagerCallback
09-29 21:41:41.492    6811-6811/org.runnerup W/System.err﹕ [ RetryingHRProviderProxy: Polar WearLink, attempt: 2 ], state: CONNECTING, request: CONNECTED, tryConnect(method: 0)
09-29 21:41:44.867    6811-6811/org.runnerup W/System.err﹕ [ RetryingHRProviderProxy: Polar WearLink, attempt: 2 ], state: CONNECTING, request: CONNECTED, connected => android.bluetooth.BluetoothSocket@7708c54
09-29 21:41:45.200    6811-6811/org.runnerup W/System.err﹕ [ RetryingHRProviderProxy: Polar WearLink, attempt: 2 ], state: CONNECTING, request: CONNECTED, reportConnected(false) mIsConnecting: true, mIsConnected: false, hrClient: org.runnerup.hr.RetryingHRProviderProxy@3d641fa7
09-29 21:41:45.210    6811-6811/org.runnerup W/System.err﹕ [ RetryingHRProviderProxy: Polar WearLink, attempt: 2 ], state: CONNECTING, request: CONNECTED, onConnectResult(false)
09-29 21:41:45.219    6811-6811/org.runnerup W/System.err﹕ [ RetryingHRProviderProxy: Polar WearLink, attempt: 3 ], state: CONNECTING, request: CONNECTED, retry in 1500ms
09-29 21:41:46.731    6811-6811/org.runnerup W/System.err﹕ [ RetryingHRProviderProxy: Polar WearLink, attempt: 3 ], state: CONNECTING, request: CONNECTED, retry connect
09-29 21:41:46.795    6811-7562/org.runnerup W/BluetoothAdapter﹕ getBluetoothService() called with no BluetoothManagerCallback
09-29 21:41:46.805    6811-6811/org.runnerup W/System.err﹕ [ RetryingHRProviderProxy: Polar WearLink, attempt: 3 ], state: CONNECTING, request: CONNECTED, tryConnect(method: 0)
09-29 21:41:50.807    6811-7562/org.runnerup W/System.err﹕ java.io.IOException: read failed, socket might closed or timeout, read ret: -1
09-29 21:41:50.807    6811-7562/org.runnerup W/System.err﹕ at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:573)
09-29 21:41:50.807    6811-7562/org.runnerup W/System.err﹕ at android.bluetooth.BluetoothSocket.readInt(BluetoothSocket.java:584)
09-29 21:41:50.807    6811-7562/org.runnerup W/System.err﹕ at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java:321)
09-29 21:41:50.807    6811-7562/org.runnerup W/System.err﹕ at org.runnerup.hr.Bt20Base.tryConnect(Bt20Base.java:356)
09-29 21:41:50.807    6811-7562/org.runnerup W/System.err﹕ at org.runnerup.hr.Bt20Base$ConnectThread.run(Bt20Base.java:392)
09-29 21:41:50.807    6811-7562/org.runnerup W/BluetoothAdapter﹕ getBluetoothService() called with no BluetoothManagerCallback
09-29 21:41:50.808    6811-6811/org.runnerup W/System.err﹕ [ RetryingHRProviderProxy: Polar WearLink, attempt: 3 ], state: CONNECTING, request: CONNECTED, closeSocket
09-29 21:41:50.822    6811-6811/org.runnerup W/System.err﹕ [ RetryingHRProviderProxy: Polar WearLink, attempt: 3 ], state: CONNECTING, request: CONNECTED, tryConnect(method: 1)
09-29 21:41:52.582    6811-6811/org.runnerup W/System.err﹕ [ RetryingHRProviderProxy: Polar WearLink, attempt: 3 ], state: CONNECTING, request: CONNECTED, connected => android.bluetooth.BluetoothSocket@12a587fd
09-29 21:41:53.353    6811-6811/org.runnerup W/System.err﹕ [ RetryingHRProviderProxy: Polar WearLink, attempt: 3 ], state: CONNECTING, request: CONNECTED, reportConnected(false) mIsConnecting: true, mIsConnected: false, hrClient: org.runnerup.hr.RetryingHRProviderProxy@3d641fa7
09-29 21:41:53.391    6811-6811/org.runnerup W/System.err﹕ [ RetryingHRProviderProxy: Polar WearLink, attempt: 3 ], state: CONNECTING, request: CONNECTED, onConnectResult(false)
09-29 21:41:53.400    6811-6811/org.runnerup W/System.err﹕ [ RetryingHRProviderProxy: Polar WearLink, attempt: 4 ], state: OPENED, request: OPENED, client.onConnectResult(false)

**Comment by bgaluszka** [comment]
Can confirm, have the same device and the same errors.

**Comment by jonasoreland** [comment]
have you tried with BLE ?

/Jonas

**Comment by tbdal** [comment]
yes i tried all options. 
with BLE the "Polar iWL" device is not showing so that i could choose it.

**Comment by bgaluszka** [comment]
Just to confirm, I've the same. If I have it paired in settings I can choose but application can't connect. If I don't have it paired in settings it doesn't show up in application so I can choose it to connect.

**Comment by jonasoreland** [comment]
is there some other app that this HRM work with ?
(preferable a "test" application)

/Jonas

**Comment by bgaluszka** [comment]
Mine works with Runkeeper https://play.google.com/store/apps/details?id=com.fitnesskeeper.runkeeper.pro and I couldn't find any app in F-Droid that does/reads HRM.

**Comment by tbdal** [comment]
runtastic works for me.
i have android studio up and running including RunnerUp sources being ready to be compiled.
If i can do something just let me know.

**Comment by jonasoreland** [comment]
do you select anything with RunKeeper or Runtastic ?

(like one can select BLE, PolarWearLink etc with RunnerUp)

**Comment by tbdal** [comment]
in runtastic it's called "weitere Brustgurte" in german

**Comment by darander** [comment]
Well, the H7 does both the old 5.3kHz protocol and BLE. I've just added the H7 as a regular BLE HRM, and that's been working flawlessly with RunnerUp for a long time. If you have a choice, do not choose PolarWearLink.

**Comment by tbdal** [comment]
strange. the Polar IWL device is not showing up after selecting BLE.
I tried both the version from f-droid and compilation of today's source.

@jonasoreland: after seeing @darander's post i'm not sure anymore it is the H7 i have here.
is there a way to find out?

**Comment by darander** [comment]
@tbdal I think you should be able to find out if it's an H7 by looking at the back of it.
Have you compared your device with pictures on the Polar web-site?

**Comment by tbdal** [comment]
i guess that's embarrassing.. so the topic needs a change ;)

it seems to be an IC:6248A-R7, see also: https://industrycanada.co/business.php?id=6248A
the front also does not have this oval shaping for the logos which the h7 has, but a parallel detail.

@bgaluszka: what is written on the back of yours?

are the fundamental differences to the sensor compared to the h7? could anyone assist in implementing the code for RunnerUp? i'm not too experienced in Android coding.

**Comment by bgaluszka** [comment]
Mine says N2965. It looks like H7 from polar site http://www.polar.com/en/products/accessories/H7_heart_rate_sensor, but nothing on mine says that this is H7, so at this point I'm just assuming it's H7 :)

**Comment by darander** [comment]
@bgaluszka mind has H7 printed in might brown (?)  on the back, just above the M on 30M. Does your state Bluetooth SMART on the front? 

I just checked my old heart rate monitor. It does say N2965 on the back, and T61 coded  on the front. That one är least, so only support the old 5.3kHz protocol.

**Comment by bgaluszka** [comment]
I've looked a bit more and I think I've this one http://www.polar.com/en/products/accessories/Polar_WearLink_transmitter_with_Bluetooth and based on FCC ID https://fccid.io/INWR7 seems like it's not H7 in the end.

**Comment by darander** [comment]
Ok, Yep then it's a Wearlink+, ie Bluetooth 2.0 and not Bluetooth 4.0(SMART). I'll leave it to someone else who has experience work those devices to look further into this. 

Good luck!

**Comment by tbdal** [comment]
google implemented the Wearlink+ in myTracks.
Maybe we can use the code?
http://stackoverflow.com/questions/12641131/polar-wearlink-bluetooth-packet

**Comment by jonasoreland** [comment]
haven't i already implemented that ??

/Jonas

**Comment by tbdal** [comment]
@jonasoreland: did you implement the same code as myTracks?
i remember vaguely myTracks worked before with the IC:6248A-R7.
so i can't figure out why it isn't with RunnerUp

**Comment by dsteuer** [comment]
Just to give data point. Runner Up 1.51, Wearlink+ device, I can pair, it works in runkeeper, 
Runner Up can not connect. How can I help? 
And btw: Many, many thanks for developing. Was waiting for such an apps without data leakage!

**Comment by PanderMusubi** [comment]
Can confirm, have the same device and the same errors for RunnerUp 1.52. the device works with https://play.google.com/store/apps/details?id=org.marco45.polarheartmonitor 

The source code is at https://github.com/marcolivierarsenault/PolarHeartRateApplication

Would be nice to have that app in F-Droid as well

**Comment by gerhardol** [comment]
Summary: Problem setting up WearLink sensors
Low priority, support for WearLink will likely be removed in new development

**Comment by PanderMusubi** [comment]
Code for it can be found at https://github.com/marcolivierarsenault/PolarHeartRateApplication see also https://play.google.com/store/apps/details?id=org.marco45.polarheartmonitor We are going to get this app also into F-Droid.

**Comment by rubliexpress** [comment]
Hello i have a h7 sensor and i want to connect it with the app. but did no success.

is this issue still valid? seems that this issue is some years old. 
Is it planned to solve the problem?
how can i help something?

thanks
best rubliexpress

**Comment by gerhardol** [comment]
The original was WearLink, which likely is obsolete now (you have to activate Experimental in 2.0).

Polar H7 is BLE so that is something different, open a new issue with versions and logs when setting up

**Comment by rubliexpress** [comment]
Hello Gerhard

Tahnks for your answer. Meanwhile I replaced the battery from my H7, tested with an other device (works good) and then I retested it with you app. --> It works well!

May I was too impatiently to wait for a good connection. ;-)

Thanks (and sorry for the disturbance)
great work
best 
rubliexpress
