### ISSUE TITLE
Garminconnect Code 302

### ISSUE THREAD

**Issue by wbrenna** [jonasoreland/runnerup#438]
Perhaps Garminconnect has changed their API. Attempting to upload yields

```
09-06 21:56:57.106 6541-6940/org.runnerup E/Garmin: GarminSynchronizer.connect() CHOOSE_URL => code: 302, msg: Moved Temporarily
09-06 21:56:58.331 6541-6940/org.runnerup E/Garmin: ticket: ***-cas
09-06 21:56:58.652 6541-6940/org.runnerup E/Garmin: attempt: 0 => code: 302
09-06 21:56:58.778 6541-6940/org.runnerup E/Garmin: attempt: 1 => code: 302
09-06 21:56:58.953 6541-6940/org.runnerup E/Garmin: attempt: 2 => code: 302
09-06 21:56:59.215 6541-6940/org.runnerup E/Garmin: attempt: 3 => code: 302
09-06 21:56:59.449 6541-6940/org.runnerup E/Garmin: attempt: 4 => code: 302
09-06 21:56:59.701 6541-6940/org.runnerup E/Garmin: attempt: 5 => code: 302
09-06 21:57:00.229 6541-6940/org.runnerup E/Garmin: attempt: 6 => code: 200
09-06 21:57:04.203 6541-6940/org.runnerup W/System.err: java.lang.Exception: Forbidden
09-06 21:57:04.203 6541-6940/org.runnerup W/System.err:     at org.runnerup.export.GarminSynchronizer.upload(GarminSynchronizer.java:463)
09-06 21:57:04.203 6541-6940/org.runnerup W/System.err:     at org.runnerup.export.SyncManager$18.doInBackground(SyncManager.java:1113)
09-06 21:57:04.203 6541-6940/org.runnerup W/System.err:     at org.runnerup.export.SyncManager$18.doInBackground(SyncManager.java:1106)
09-06 21:57:04.203 6541-6940/org.runnerup W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
09-06 21:57:04.203 6541-6940/org.runnerup W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-06 21:57:04.203 6541-6940/org.runnerup W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
09-06 21:57:04.203 6541-6940/org.runnerup W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
09-06 21:57:04.204 6541-6940/org.runnerup W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
09-06 21:57:04.204 6541-6940/org.runnerup W/System.err:     at java.lang.Thread.run(Thread.java:818)
```

**Comment by Marx2** [comment]
I confirm. I cannot upload trainings.

**Comment by jonasoreland** [comment]
can anyone check if https://github.com/cpfair/tapiriik/tree/master/tapiriik/services has done any updates to their garmin adapter ??

**Comment by moobyfr** [comment]
I saw a mail from one company complaning about the move on garminconnect changes:
The API is now non-free-as-beer, $5000 . http://developer.garmin.com/garmin-connect-api/overview/

**Comment by nebmo** [comment]
$5000??? Does this mean that integration with garmin is gone for good?

**Comment by Marx2** [comment]
It's information from March and as I understand it apply only form mass downloading data of all users FROM Garmin site.
Fix is possible, you can read for example this:
https://ro-z.net/blog/connectstats/fix-for-connection-issue-connectstats-3-2-1/
Something like "double logging in" is needed.

**Comment by jonasoreland** [comment]
investigated this somewhat today.
1) i needed to change password, (on the web) or else it refused to connect
2) i now get the java.lang.Exception: Forbidden too...which is the problem.

I have no idea how to fix 2)

**Comment by gerhardol** [comment]
Garmin synch will be hidden/disabled when #590 is merged
