### ISSUE TITLE
Instant crash when trying to scan for bluetooth HRM device

### ISSUE THREAD

**Issue by craftyguy** [jonasoreland/runnerup#763]
Immediately on tapping 'SCAN' when on the HRM settings screen, the app is force-closed. The relevant part of the logcat when this happens is here (full output from running app is attached as a file):

```
03-20 08:39:25.862  6307  6333 D OpenGLRenderer: endAllActiveAnimators on 0x73ebb1c400 (ListView) with handle 0x73ebb90e20
03-20 08:39:26.602  6307  6307 D AndroidRuntime: Shutting down VM
03-20 08:39:26.603  6307  6307 E AndroidRuntime: FATAL EXCEPTION: main
03-20 08:39:26.603  6307  6307 E AndroidRuntime: Process: org.runnerup.alpha, PID: 6307
03-20 08:39:26.603  6307  6307 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String org.runnerup.d.i.b()' on a null object reference
03-20 08:39:26.603  6307  6307 E AndroidRuntime:        at org.runnerup.view.HRSettingsActivity.r(Unknown Source:28)
03-20 08:39:26.603  6307  6307 E AndroidRuntime:        at org.runnerup.view.HRSettingsActivity.d(Unknown Source:0)
03-20 08:39:26.603  6307  6307 E AndroidRuntime:        at org.runnerup.view.HRSettingsActivity$9.onClick(Unknown Source:30)
03-20 08:39:26.603  6307  6307 E AndroidRuntime:        at android.view.View.performClick(View.java:6294)
03-20 08:39:26.603  6307  6307 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:24770)
03-20 08:39:26.603  6307  6307 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:790)
03-20 08:39:26.603  6307  6307 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
03-20 08:39:26.603  6307  6307 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
03-20 08:39:26.603  6307  6307 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6494)
03-20 08:39:26.603  6307  6307 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-20 08:39:26.603  6307  6307 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
03-20 08:39:26.603  6307  6307 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
03-20 08:39:26.608  3260  5386 W ActivityManager:   Force finishing activity org.runnerup.alpha/org.runnerup.view.HRSettingsActivity
```

RunnerUp version: 2.0.0.2
Android: 8.1 (LineageOS 15.1)
Device: Nexus 5X

[runnerup logcat](https://github.com/jonasoreland/runnerup/files/2988991/runnerup.log)

**Comment by craftyguy** [comment]
I'm sorry, this was fixed in 2.0.0.3, for some reason (totally my fault) I did not see that this was available for download!

**Comment by gerhardol** [comment]
2.0 is not the official release yet, good to see that this works (there are a few corrections, I was not aware of this FC though).

**Comment by craftyguy** [comment]
Yea I know it's not the official releae, but I want to use it to (hopefully) give feedback :)
