### ISSUE TITLE
Not declaring Google Play version makes application crash on 4.4.4

### ISSUE THREAD

**Issue by bagage** [jonasoreland/runnerup#77]
In AndroidManifest.xml, this is currently commented for Froyok backward compability:

```XML
<!-- <meta-data android:name="com.google.android.gms.version"         
              android:value="@integer/google_play_services_version" /> -->
```

However the app crashes on Galaxy Nexus @ Android 4.4.4, when *saving a race* or *clicking on it in the history tab*. Full trace is:

```
07-28 20:52:43.513: I/ActivityManager(23173): START u0 {cmp=org.runnerup/.view.DetailActivity (has extras)} from pid 9756
07-28 20:52:43.591: E/ActivityThread(9756): Failed to inflate
07-28 20:52:43.591: E/ActivityThread(9756): android.view.InflateException: Binary XML file line #173: Error inflating class fragment
07-28 20:52:43.591: E/ActivityThread(9756): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
07-28 20:52:43.591: E/ActivityThread(9756): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
07-28 20:52:43.591: E/ActivityThread(9756): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
07-28 20:52:43.591: E/ActivityThread(9756): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
07-28 20:52:43.591: E/ActivityThread(9756): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
07-28 20:52:43.591: E/ActivityThread(9756): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
07-28 20:52:43.591: E/ActivityThread(9756): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
07-28 20:52:43.591: E/ActivityThread(9756): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
07-28 20:52:43.591: E/ActivityThread(9756): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
07-28 20:52:43.591: E/ActivityThread(9756): 	at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:290)
07-28 20:52:43.591: E/ActivityThread(9756): 	at android.app.Activity.setContentView(Activity.java:1936)
07-28 20:52:43.591: E/ActivityThread(9756): 	at org.runnerup.view.DetailActivity.onCreate(DetailActivity.java:135)
07-28 20:52:43.591: E/ActivityThread(9756): 	at android.app.Activity.performCreate(Activity.java:5312)
07-28 20:52:43.591: E/ActivityThread(9756): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
07-28 20:52:43.591: E/ActivityThread(9756): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2179)
07-28 20:52:43.591: E/ActivityThread(9756): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2274)
07-28 20:52:43.591: E/ActivityThread(9756): 	at android.app.ActivityThread.access$800(ActivityThread.java:141)
07-28 20:52:43.591: E/ActivityThread(9756): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202)
07-28 20:52:43.591: E/ActivityThread(9756): 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-28 20:52:43.591: E/ActivityThread(9756): 	at android.os.Looper.loop(Looper.java:136)
07-28 20:52:43.591: E/ActivityThread(9756): 	at android.app.ActivityThread.main(ActivityThread.java:5053)
07-28 20:52:43.591: E/ActivityThread(9756): 	at java.lang.reflect.Method.invokeNative(Native Method)
07-28 20:52:43.591: E/ActivityThread(9756): 	at java.lang.reflect.Method.invoke(Method.java:515)
07-28 20:52:43.591: E/ActivityThread(9756): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
07-28 20:52:43.591: E/ActivityThread(9756): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
07-28 20:52:43.591: E/ActivityThread(9756): 	at dalvik.system.NativeStart.main(Native Method)
07-28 20:52:43.591: E/ActivityThread(9756): Caused by: java.lang.IllegalStateException: The meta-data tag in your app's AndroidManifest.xml does not have the right value.  Expected 4242000 but found 0.  You must have the following declaration within the <application> element:     <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
07-28 20:52:43.591: E/ActivityThread(9756): 	at com.google.android.gms.common.GooglePlayServicesUtil.n(Unknown Source)
07-28 20:52:43.591: E/ActivityThread(9756): 	at com.google.android.gms.common.GooglePlayServicesUtil.isGooglePlayServicesAvailable(Unknown Source)
07-28 20:52:43.591: E/ActivityThread(9756): 	at com.google.android.gms.maps.internal.q.v(Unknown Source)
07-28 20:52:43.591: E/ActivityThread(9756): 	at com.google.android.gms.maps.internal.q.u(Unknown Source)
07-28 20:52:43.591: E/ActivityThread(9756): 	at com.google.android.gms.maps.MapsInitializer.initialize(Unknown Source)
07-28 20:52:43.591: E/ActivityThread(9756): 	at com.google.android.gms.maps.SupportMapFragment$b.ex(Unknown Source)
07-28 20:52:43.591: E/ActivityThread(9756): 	at com.google.android.gms.maps.SupportMapFragment$b.a(Unknown Source)
07-28 20:52:43.591: E/ActivityThread(9756): 	at com.google.android.gms.dynamic.a.a(Unknown Source)
07-28 20:52:43.591: E/ActivityThread(9756): 	at com.google.android.gms.dynamic.a.onInflate(Unknown Source)
07-28 20:52:43.591: E/ActivityThread(9756): 	at com.google.android.gms.maps.SupportMapFragment.onInflate(Unknown Source)
07-28 20:52:43.591: E/ActivityThread(9756): 	at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:290)
07-28 20:52:43.591: E/ActivityThread(9756): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:685)
07-28 20:52:43.591: E/ActivityThread(9756): 	... 25 more
07-28 20:52:43.591: D/AndroidRuntime(9756): Shutting down VM
07-28 20:52:43.591: W/dalvikvm(9756): threadid=1: thread exiting with uncaught exception (group=0x418a4ba8)
07-28 20:52:43.599: E/AndroidRuntime(9756): FATAL EXCEPTION: main
07-28 20:52:43.599: E/AndroidRuntime(9756): Process: org.runnerup, PID: 9756
07-28 20:52:43.599: E/AndroidRuntime(9756): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.runnerup/org.runnerup.view.DetailActivity}: android.view.InflateException: Binary XML file line #173: Error inflating class fragment
07-28 20:52:43.599: E/AndroidRuntime(9756): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2225)
07-28 20:52:43.599: E/AndroidRuntime(9756): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2274)
07-28 20:52:43.599: E/AndroidRuntime(9756): 	at android.app.ActivityThread.access$800(ActivityThread.java:141)
07-28 20:52:43.599: E/AndroidRuntime(9756): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202)
07-28 20:52:43.599: E/AndroidRuntime(9756): 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-28 20:52:43.599: E/AndroidRuntime(9756): 	at android.os.Looper.loop(Looper.java:136)
07-28 20:52:43.599: E/AndroidRuntime(9756): 	at android.app.ActivityThread.main(ActivityThread.java:5053)
07-28 20:52:43.599: E/AndroidRuntime(9756): 	at java.lang.reflect.Method.invokeNative(Native Method)
07-28 20:52:43.599: E/AndroidRuntime(9756): 	at java.lang.reflect.Method.invoke(Method.java:515)
07-28 20:52:43.599: E/AndroidRuntime(9756): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
07-28 20:52:43.599: E/AndroidRuntime(9756): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
07-28 20:52:43.599: E/AndroidRuntime(9756): 	at dalvik.system.NativeStart.main(Native Method)
07-28 20:52:43.599: E/AndroidRuntime(9756): Caused by: android.view.InflateException: Binary XML file line #173: Error inflating class fragment
07-28 20:52:43.599: E/AndroidRuntime(9756): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
07-28 20:52:43.599: E/AndroidRuntime(9756): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
07-28 20:52:43.599: E/AndroidRuntime(9756): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
07-28 20:52:43.599: E/AndroidRuntime(9756): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
07-28 20:52:43.599: E/AndroidRuntime(9756): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
07-28 20:52:43.599: E/AndroidRuntime(9756): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
07-28 20:52:43.599: E/AndroidRuntime(9756): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
07-28 20:52:43.599: E/AndroidRuntime(9756): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
07-28 20:52:43.599: E/AndroidRuntime(9756): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
07-28 20:52:43.599: E/AndroidRuntime(9756): 	at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:290)
07-28 20:52:43.599: E/AndroidRuntime(9756): 	at android.app.Activity.setContentView(Activity.java:1936)
07-28 20:52:43.599: E/AndroidRuntime(9756): 	at org.runnerup.view.DetailActivity.onCreate(DetailActivity.java:135)
07-28 20:52:43.599: E/AndroidRuntime(9756): 	at android.app.Activity.performCreate(Activity.java:5312)
07-28 20:52:43.599: E/AndroidRuntime(9756): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
07-28 20:52:43.599: E/AndroidRuntime(9756): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2179)
07-28 20:52:43.599: E/AndroidRuntime(9756): 	... 11 more
07-28 20:52:43.599: E/AndroidRuntime(9756): Caused by: java.lang.IllegalStateException: The meta-data tag in your app's AndroidManifest.xml does not have the right value.  Expected 4242000 but found 0.  You must have the following declaration within the <application> element:     <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
07-28 20:52:43.599: E/AndroidRuntime(9756): 	at com.google.android.gms.common.GooglePlayServicesUtil.n(Unknown Source)
07-28 20:52:43.599: E/AndroidRuntime(9756): 	at com.google.android.gms.common.GooglePlayServicesUtil.isGooglePlayServicesAvailable(Unknown Source)
07-28 20:52:43.599: E/AndroidRuntime(9756): 	at com.google.android.gms.maps.internal.q.v(Unknown Source)
07-28 20:52:43.599: E/AndroidRuntime(9756): 	at com.google.android.gms.maps.internal.q.u(Unknown Source)
07-28 20:52:43.599: E/AndroidRuntime(9756): 	at com.google.android.gms.maps.MapsInitializer.initialize(Unknown Source)
07-28 20:52:43.599: E/AndroidRuntime(9756): 	at com.google.android.gms.maps.SupportMapFragment$b.ex(Unknown Source)
07-28 20:52:43.599: E/AndroidRuntime(9756): 	at com.google.android.gms.maps.SupportMapFragment$b.a(Unknown Source)
07-28 20:52:43.599: E/AndroidRuntime(9756): 	at com.google.android.gms.dynamic.a.a(Unknown Source)
07-28 20:52:43.599: E/AndroidRuntime(9756): 	at com.google.android.gms.dynamic.a.onInflate(Unknown Source)
07-28 20:52:43.599: E/AndroidRuntime(9756): 	at com.google.android.gms.maps.SupportMapFragment.onInflate(Unknown Source)
07-28 20:52:43.599: E/AndroidRuntime(9756): 	at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:290)
07-28 20:52:43.599: E/AndroidRuntime(9756): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:685)
07-28 20:52:43.599: E/AndroidRuntime(9756): 	... 25 more
07-28 20:52:43.599: W/ActivityManager(23173):   Force finishing activity org.runnerup/.view.DetailActivity
07-28 20:52:43.606: W/ActivityManager(23173):   Force finishing activity org.runnerup/.view.MainLayout
07-28 20:52:44.106: W/ActivityManager(23173): Activity pause timeout for ActivityRecord{4259f5d0 u0 org.runnerup/.view.DetailActivity t105 f}
07-28 20:52:44.286: I/ActivityManager(23173): Killing 9105:com.google.android.gms.wearable/u0a17 (adj 15): empty #17
07-28 20:52:54.286: W/ActivityManager(23173): Activity destroy timeout for ActivityRecord{424ddb98 u0 org.runnerup/.view.MainLayout t105 f}
07-28 20:52:54.286: W/ActivityManager(23173): Activity destroy timeout for ActivityRecord{4259f5d0 u0 org.runnerup/.view.DetailActivity t105 f}
```

**Comment by jonasoreland** [comment]
i think this was a build error somehow,
but latest has split out froyo, so now it should be ok.
