### ISSUE TITLE
App crashes when testing app

### ISSUE THREAD

**Issue by WangGuox1n** [jonasoreland/runnerup#846]
Hi, I developed an automatic-testing tool and it detected these exceptions in your app(version 2.0.0 Alpha 2). I would like to know if you consider them as bug?
Device Information:  android 4.4,   Genymotion  Custom Phone.

when I start the app from Android Studio, the app crashes.
![screenshot-2019-09-06_21 53 54 559](https://user-images.githubusercontent.com/31890594/64434369-fd30af00-d0f2-11e9-9391-5026a03b2caa.png)

```
E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: org.runnerup, PID: 3051
                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{org.runnerup/org.runnerup.view.MainLayout}: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.runnerup/org.runnerup.view.StartActivity}: android.view.InflateException: Binary XML file line #2: Error inflating class android.support.design.widget.FloatingActionButton
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
                                                     at android.app.ActivityThread.access800(ActivityThread.java:135)
                                                     at android.app.ActivityThreadH.handleMessage(ActivityThread.java:1196)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInitMethodAndArgsCaller.run(ZygoteInit.java:785)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                     at dalvik.system.NativeStart.main(Native Method)
                                                  Caused by: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.runnerup/org.runnerup.view.StartActivity}: android.view.InflateException: Binary XML file line #2: Error inflating class android.support.design.widget.FloatingActionButton
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
                                                     at android.app.ActivityThread.startActivityNow(ActivityThread.java:2024)
                                                     at android.app.LocalActivityManager.moveToState(LocalActivityManager.java:135)
                                                     at android.app.LocalActivityManager.startActivity(LocalActivityManager.java:347)
                                                     at android.widget.TabHostIntentContentStrategy.getContentView(TabHost.java:749)
                                                     at android.widget.TabHost.setCurrentTab(TabHost.java:413)
                                                     at android.widget.TabHost.addTab(TabHost.java:240)
                                                     at org.runnerup.view.MainLayout.onCreate(MainLayout.java:146)
                                                     at android.app.Activity.performCreate(Activity.java:5231)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233) 
                                                     at android.app.ActivityThread.access800(ActivityThread.java:135) 
                                                     at android.app.ActivityThreadH.handleMessage(ActivityThread.java:1196) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:136) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:515) 
                                                     at com.android.internal.os.ZygoteInitMethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                     at dalvik.system.NativeStart.main(Native Method) 
                                                  Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class android.support.design.widget.FloatingActionButton
                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:620)
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
                                                     at android.view.LayoutInflater.parseInclude(LayoutInflater.java:816)
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:745)
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                     at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280)
                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                     at org.runnerup.view.StartActivity.onCreate(StartActivity.java:171)
                                                     at android.app.Activity.performCreate(Activity.java:5231)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
                                                     at android.app.ActivityThread.startActivityNow(ActivityThread.java:2024) 
                                                     at android.app.LocalActivityManager.moveToState(LocalActivityManager.java:135) 
                                                     at android.app.LocalActivityManager.startActivity(LocalActivityManager.java:347) 
                                                     at android.widget.TabHostIntentContentStrategy.getContentView(TabHost.java:749) 
                                                     at android.widget.TabHost.setCurrentTab(TabHost.java:413) 
                                                     at android.widget.TabHost.addTab(TabHost.java:240) 
                                                     at org.runnerup.view.MainLayout.onCreate(MainLayout.java:146) 
                                                     at android.app.Activity.performCreate(Activity.java:5231) 
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233) 
                                                     at android.app.ActivityThread.access800(ActivityThread.java:135) 
                                                     at android.app.ActivityThreadH.handleMessage(ActivityThread.java:1196) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:136) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:515) 
                                                     at com.android.internal.os.ZygoteInitMethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                     at dalvik.system.NativeStart.main(Native Method) 
                                                  Caused by: java.lang.reflect.InvocationTargetException
                                                     at java.lang.reflect.Constructor.constructNative(Native Method)
                                                     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:594)
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
                                                     at android.view.LayoutInflater.parseInclude(LayoutInflater.java:816) 
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:745) 
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                     at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280) 
                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                     at org.runnerup.view.StartActivity.onCreate(StartActivity.java:171) 
                                                     at android.app.Activity.performCreate(Activity.java:5231) 
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148) 
                                                     at android.app.ActivityThread.startActivityNow(ActivityThread.java:2024) 
                                                     at android.app.LocalActivityManager.moveToState(LocalActivityManager.java:135) 
                                                     at android.app.LocalActivityManager.startActivity(LocalActivityManager.java:347) 
                                                     at android.widget.TabHostIntentContentStrategy.getContentView(TabHost.java:749) 
                                                     at android.widget.TabHost.setCurrentTab(TabHost.java:413) 
                                                     at android.widget.TabHost.addTab(TabHost.java:240) 
                                                     at org.runnerup.view.MainLayout.onCreate(MainLayout.java:146) 
                                                     at android.app.Activity.performCreate(Activity.java:5231) 
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233) 
                                                     at android.app.ActivityThread.access800(ActivityThread.java:135) 
                                                     at android.app.ActivityThreadH.handleMessage(ActivityThread.java:1196) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:136) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:515) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                     at dalvik.system.NativeStart.main(Native Method) 
                                                  Caused by: java.lang.IllegalArgumentException: You need to use a Theme.AppCompat theme (or descendant) with the design library.
                                                     at android.support.design.widget.ThemeUtils.checkAppCompatTheme(ThemeUtils.java:36)
                                                     at android.support.design.widget.FloatingActionButton.<init>(FloatingActionButton.java:153)
```

**Comment by WangGuox1n** [comment]
Second exception:
```
E/AndroidRuntime( 2526): FATAL EXCEPTION: main
E/AndroidRuntime( 2526): Process: org.runnerup, PID: 2526
E/AndroidRuntime( 2526): android.content.ActivityNotFoundException: Unable to find explicit activity class {org.runnerup.alpha/org.runnerup.view.AudioCueSettingsActivity}; have you declared this activity in your AndroidManifest.xml?
E/AndroidRuntime( 2526): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1628)
E/AndroidRuntime( 2526): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1424)
E/AndroidRuntime( 2526): 	at android.app.Activity.startActivityFromChild(Activity.java:3906)
E/AndroidRuntime( 2526): 	at android.app.Activity.startActivityFromChild(Activity.java:3882)
E/AndroidRuntime( 2526): 	at android.app.Activity.startActivityForResult(Activity.java:3455)
E/AndroidRuntime( 2526): 	at android.app.Activity.startActivityForResult(Activity.java:3385)
E/AndroidRuntime( 2526): 	at android.app.Activity.startActivity(Activity.java:3627)
E/AndroidRuntime( 2526): 	at android.app.Activity.startActivity(Activity.java:3595)
E/AndroidRuntime( 2526): 	at android.preference.Preference.performClick(Preference.java:970)
E/AndroidRuntime( 2526): 	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:215)
E/AndroidRuntime( 2526): 	at android.widget.AdapterView.performItemClick(AdapterView.java:299)
E/AndroidRuntime( 2526): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1113)
E/AndroidRuntime( 2526): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:2911)
E/AndroidRuntime( 2526): 	at android.widget.AbsListView$3.run(AbsListView.java:3645)
E/AndroidRuntime( 2526): 	at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime( 2526): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 2526): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 2526): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime( 2526): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 2526): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 2526): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime( 2526): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime( 2526): 	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by WangGuox1n** [comment]
There are many exception like second exception: `android.content.ActivityNotFoundException: Unable to find explicit activity class {org.runnerup.alpha/org.runnerup.view.xxxxxxxActivity}; have you declared this activity in your AndroidManifest.xml?`
wondering what caused this kind of exception?

**Comment by gerhardol** [comment]
> Hi, I developed an automatic-testing tool and it detected these exceptions in your app(version 2.0.0 Alpha 2). 

Cool

>I would like to know if you consider them as bug?

Hard to say

> Error inflating class android.support.design.widget.FloatingActionButton

This is fixed in later versions, seen below Android 5
Please retest on latest version

> wondering what caused this kind of exception?

This is probably that the activity is "internal"  without a real need to be declared in the manifest.

**Comment by gerhardol** [comment]
Closing due to age, open a new if there are issues in latest release
