### ISSUE TITLE
crash when adding manual entry

### ISSUE THREAD

**Issue by anlalalu** [jonasoreland/runnerup#863]
###### Reproduction Steps

1. tap 'history'
2. tap 'Distance' and a dialog appears
3. press back
4. tap 'Distance' again

###### Stack Trace
E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: org.runnerup.debug, PID: 3647
                                                 java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
                                                     at android.view.ViewGroup.addViewInner(ViewGroup.java:3562)
                                                     at android.view.ViewGroup.addView(ViewGroup.java:3415)
                                                     at android.view.ViewGroup.addView(ViewGroup.java:3360)
                                                     at android.view.ViewGroup.addView(ViewGroup.java:3336)
                                                     at org.runnerup.widget.SpinnerPresenter$6.onClick(SpinnerPresenter.java:367)
                                                     at android.view.View.performClick(View.java:4438)
                                                     at android.view.View$PerformClick.run(View.java:18422)
                                                     at android.os.Handler.handleCallback(Handler.java:733)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                     at dalvik.system.NativeStart.main(Native Method)

###### Debug info
App Version = 2.0.3.0

Android Version = 4.4.4

**Comment by gerhardol** [comment]
Added PR
Thanks
