### ISSUE TITLE
App crashes when no TTS engine present

### ISSUE THREAD

**Issue by DIWesser** [jonasoreland/runnerup#958]
Definitely an edge case but, the app crashes when android does not have a TTS engine enabled (e.g. the default LineageOS with F-Droid setup).

**Comment by gerhardol** [comment]
With a logcat, an attempt to avoid this could be done.
It is best if someone with such a device makes a correction, follow up are often needed.

**Comment by TheLastProject** [comment]
Logcat:

```
2020-09-01 19:57:27.103 14015-14015/org.runnerup.debug E/org.runnerup.workout.feedback.RUTextToSpeech: buffer speak: interval
2020-09-01 19:57:27.103 14015-14015/org.runnerup.debug E/InputEventReceiver: Exception dispatching input event.
2020-09-01 19:57:27.103 14015-14015/org.runnerup.debug E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
2020-09-01 19:57:27.112 14015-14015/org.runnerup.debug E/MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.speech.tts.TextToSpeech.speak(java.lang.String, int, java.util.HashMap)' on a null object reference
        at org.runnerup.workout.feedback.RUTextToSpeech.emit(RUTextToSpeech.java:202)
        at org.runnerup.view.AudioCueSettingsActivity$2.lambda$$0$AudioCueSettingsActivity$2(AudioCueSettingsActivity.java:342)
        at org.runnerup.view.-$$Lambda$AudioCueSettingsActivity$2$HbhHwkHsFeFHGfF-JO9BzjVPE04.onInit(Unknown Source:2)
        at android.speech.tts.TextToSpeech.dispatchOnInit(TextToSpeech.java:831)
        at android.speech.tts.TextToSpeech.initTts(TextToSpeech.java:809)
        at android.speech.tts.TextToSpeech.<init>(TextToSpeech.java:740)
        at android.speech.tts.TextToSpeech.<init>(TextToSpeech.java:719)
        at android.speech.tts.TextToSpeech.<init>(TextToSpeech.java:703)
        at org.runnerup.view.AudioCueSettingsActivity$2.onPreferenceClick(AudioCueSettingsActivity.java:360)
        at android.preference.Preference.performClick(Preference.java:1137)
        at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:249)
        at android.widget.AdapterView.performItemClick(AdapterView.java:318)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1159)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3136)
        at android.widget.AbsListView.onTouchUp(AbsListView.java:4064)
        at android.widget.AbsListView.onTouchEvent(AbsListView.java:3822)
        at android.view.View.dispatchTouchEvent(View.java:12513)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3024)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2705)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:440)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1830)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3401)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:398)
        at android.view.View.dispatchPointerEvent(View.java:12752)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5113)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4916)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4433)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4486)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4452)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4592)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4460)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4649)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4433)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4486)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4452)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4460)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4433)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7099)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7068)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7029)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7202)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
        at android.os.MessageQueue.nativePollOnce(Native Method)
    	at 
2020-09-01 19:57:27.112 14015-14015/org.runnerup.debug D/AndroidRuntime: Shutting down VM
2020-09-01 19:57:27.114 14015-14015/org.runnerup.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.runnerup.debug, PID: 14015
    java.lang.NullPointerException: Attempt to invoke virtual method 'int android.speech.tts.TextToSpeech.speak(java.lang.String, int, java.util.HashMap)' on a null object reference
        at org.runnerup.workout.feedback.RUTextToSpeech.emit(RUTextToSpeech.java:202)
        at org.runnerup.view.AudioCueSettingsActivity$2.lambda$$0$AudioCueSettingsActivity$2(AudioCueSettingsActivity.java:342)
        at org.runnerup.view.-$$Lambda$AudioCueSettingsActivity$2$HbhHwkHsFeFHGfF-JO9BzjVPE04.onInit(Unknown Source:2)
        at android.speech.tts.TextToSpeech.dispatchOnInit(TextToSpeech.java:831)
        at android.speech.tts.TextToSpeech.initTts(TextToSpeech.java:809)
        at android.speech.tts.TextToSpeech.<init>(TextToSpeech.java:740)
        at android.speech.tts.TextToSpeech.<init>(TextToSpeech.java:719)
        at android.speech.tts.TextToSpeech.<init>(TextToSpeech.java:703)
        at org.runnerup.view.AudioCueSettingsActivity$2.onPreferenceClick(AudioCueSettingsActivity.java:360)
        at android.preference.Preference.performClick(Preference.java:1137)
        at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:249)
        at android.widget.AdapterView.performItemClick(AdapterView.java:318)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1159)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3136)
        at android.widget.AbsListView.onTouchUp(AbsListView.java:4064)
        at android.widget.AbsListView.onTouchEvent(AbsListView.java:3822)
        at android.view.View.dispatchTouchEvent(View.java:12513)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3024)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2705)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:440)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1830)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3401)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:398)
        at android.view.View.dispatchPointerEvent(View.java:12752)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5113)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4916)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4433)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4486)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4452)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4592)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4460)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4649)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4433)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4486)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4452)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4460)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4433)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7099)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7068)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7029)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7202)
2020-09-01 19:57:27.115 14015-14015/org.runnerup.debug E/AndroidRuntime:     at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

So, simply put, instantiating an instance of RUTextToSpeech will return a null if there is no Text to Speech engine available.

The funny part is, the Android developers knew this could happen, see the following note in the `initTts` function of `android.speech.tts.TextToSpeech`:

```
        // NOTE: The API currently does not allow the caller to query whether
        // they are actually connected to any engine. This might fail for various
        // reasons like if the user disables all her TTS engines.
```

I can work on fixing this myself when I have time.

**Comment by TheLastProject** [comment]
My plan to fix this is as follows:

If:
- The user tries to start a workout with any audio cue enabled
- The user presses the Test Audio Cue button

Then:
- Check if TTS is available and if not, pop up a dialog looking as follows:

```
No TTS engine available, audio cues will not work. Please make sure you have installed and configured at least one TTS engine.

[Cancel workout] [Ignore]
```

Need to also find some way to explain to the user how to get a TTS engine. https://f-droid.org/en/packages/edu.cmu.cs.speech.tts.flite/ seems to be the only one available on F-Droid. The user will likely have no Google Play Store as `Google Text To Speech` seems to be part of the default Google Apps, so I am not sure how we can give any further instructions. Maybe a wiki page to link to?

**Comment by gerhardol** [comment]
The first change should be to return if textToSpeech is null in speak(), speakWithMute() and emit()
I may do that but will welcome a better way to prent to the user.
I agree with a wiki page.
